name: Format
on: [push, pull_request]
jobs:
  lint:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Node.js version from .nvmrc
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.get-node-version.outputs.NODE_VERSION }}'

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: |
          npm run format:check
